# Generated by Django 5.2.16 on 2026-07-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('standard_shipping_fee', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('express_shipping_fee', models.DecimalField(decimal_places=2, default=400, max_digits=10)),
                ('urgent_shipping_fee', models.DecimalField(decimal_places=2, default=650, max_digits=10)),
            ],
        ),
    ]
