import { useMemo, useState, type ReactNode } from 'react';
import {
  BarChart3, Box, Image, ShoppingBag, Users, Tag, Settings, LogOut, Plus,
  Search, Pencil, Trash2, GripVertical, Upload, X,
} from 'lucide-react';
import LiveProductQueue from './liveproductqueue';
import OperationsPanel from './operationspanel';

type Section = 'dashboard' | 'products' | 'banners' | 'orders' | 'vendors' | 'pricing' | 'settings';
type OrderStatus = 'Delivered' | 'Processing' | 'Pending' | 'Cancelled';

const products = [
  { name: 'Wireless Noise-Cancelling Headphones', category: 'Electronics', price: 129.99, stock: 45, status: 'Active', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=80&q=80' },
  { name: 'Linen Blend Midi Dress', category: 'Fashion', price: 54, stock: 12, status: 'Active', image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=80&q=80' },
  { name: 'Ceramic Pour-Over Coffee Set', category: 'Home & Living', price: 42.5, stock: 8, status: 'Draft', image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=80&q=80' },
  { name: 'Minimalist Everyday Sneakers', category: 'Fashion', price: 85, stock: 0, status: 'Active', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=80&q=80' },
  { name: 'Modern Brass Table Lamp', category: 'Home & Living', price: 68, stock: 24, status: 'Active', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=80&q=80' },
  { name: 'Classic Leather Tote Bag', category: 'Fashion', price: 145, stock: 5, status: 'Draft', image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=80&q=80' },
  { name: 'Minimalist Leather Watch', category: 'Fashion', price: 95, stock: 18, status: 'Active', image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=80&q=80' },
  { name: 'Smart Fitness Tracker', category: 'Electronics', price: 59.99, stock: 32, status: 'Active', image: 'https://images.unsplash.com/photo-1557935728-e6d1eaabe558?auto=format&fit=crop&w=80&q=80' },
];
const orders: { id: string; customer: string; product: string; total: number; status: OrderStatus }[] = [
  { id: '#ORD-8847', customer: 'Sarah Jenkins', product: 'Ceramic Pour-Over Set', total: 42.5, status: 'Delivered' },
  { id: '#ORD-8848', customer: 'Mike Ross', product: 'Wireless Headphones', total: 129.99, status: 'Processing' },
  { id: '#ORD-8849', customer: 'Emily Chen', product: 'Linen Blend Dress', total: 54, status: 'Pending' },
  { id: '#ORD-8850', customer: 'David Kim', product: 'Minimalist Sneakers', total: 85, status: 'Delivered' },
  { id: '#ORD-8851', customer: 'Jessica Alba', product: 'Brass Table Lamp', total: 68, status: 'Processing' },
  { id: '#ORD-8852', customer: 'Tom Hardy', product: 'Classic Leather Tote', total: 145, status: 'Cancelled' },
];
const banners = [
  { title: 'Discover Your Next Favorite Find', subtitle: 'Shop handpicked collections', slot: 'Hero slot 1', image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=420&q=80' },
  { title: 'Tech That Fits Your Life', subtitle: 'Upgrade your essentials', slot: 'Hero slot 2', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=420&q=80' },
  { title: 'Make Your Space Feel Like Home', subtitle: 'Cozy decor, candles', slot: 'Hero slot 3', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=420&q=80' },
];

function Status({ children }: { children: OrderStatus | string }) {
  const styles: Record<string, string> = { Delivered: 'bg-emerald-100 text-emerald-700', Active: 'bg-emerald-100 text-emerald-700', Processing: 'bg-blue-100 text-blue-700', Pending: 'bg-amber-100 text-amber-700', Cancelled: 'bg-red-100 text-red-700', Draft: 'bg-slate-100 text-slate-600' };
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${styles[children] || styles.Draft}`}>{children}</span>;
}
function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`rounded-2xl border border-[#eee4dc] bg-white shadow-sm ${className}`}>{children}</div>; }
function Money({ value }: { value: number }) { return <>${value.toLocaleString(undefined, { minimumFractionDigits: 2 })}</>; }

export default function AdminPanel(): JSX.Element {
  const [section, setSection] = useState<Section>('dashboard');
  const [productPanel, setProductPanel] = useState(false);
  const [orderFilter, setOrderFilter] = useState<'All' | OrderStatus>('All');
  const [query, setQuery] = useState('');
  const nav: { key: Section; label: string; icon: typeof BarChart3 }[] = [
    { key: 'dashboard', label: 'Dashboard', icon: BarChart3 }, { key: 'products', label: 'Products', icon: Box }, { key: 'banners', label: 'Banners', icon: Image }, { key: 'orders', label: 'Orders', icon: ShoppingBag }, { key: 'vendors', label: 'Vendors', icon: Users }, { key: 'pricing', label: 'Pricing', icon: Tag }, { key: 'settings', label: 'Settings', icon: Settings },
  ];
  const title: Record<Section, string> = { dashboard: 'Dashboard Overview', products: 'Products', banners: 'Banner Manager', orders: 'Orders', vendors: 'Vendors', pricing: 'Pricing Manager', settings: 'Store Settings' };
  const filteredProducts = useMemo(() => products.filter((p) => p.name.toLowerCase().includes(query.toLowerCase())), [query]);

  return <div className="min-h-screen bg-[#fcf8f5] font-sans text-[#101a2e] lg:flex">
    <aside className="flex shrink-0 flex-col bg-[#1e1f21] text-[#a9b4c7] lg:sticky lg:top-0 lg:h-screen lg:w-64">
      <div className="flex h-20 items-center justify-between border-b border-[#29313e] px-6"><span className="text-xl font-extrabold text-[#db6b39]">DUOBRO Admin</span><Settings size={19} /></div>
      <nav className="flex gap-2 overflow-x-auto p-3 lg:block lg:space-y-2 lg:p-4">{nav.map(({ key, label, icon: Icon }) => <button key={key} onClick={() => { setSection(key); setProductPanel(false); }} className={`flex shrink-0 items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold transition-colors lg:w-full ${section === key ? 'bg-[#cf6637] text-white' : 'hover:bg-[#282a2e] hover:text-white'}`}><Icon size={19} />{label}</button>)}</nav>
      <div className="mt-auto hidden border-t border-[#29313e] p-5 lg:flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#cf6637] text-sm font-bold text-white">AR</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-white">Alex Rahman</p><p className="text-xs">Super Admin</p></div><LogOut size={19} /></div>
    </aside>

    <main className="min-w-0 flex-1 p-5 sm:p-7 lg:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><h1 className="text-2xl font-extrabold tracking-tight">{title[section]}</h1>{section === 'products' && <div className="flex gap-3"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products..." className="w-56 rounded-lg border border-[#ead8ca] bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-[#cf6637]" /></label><button onClick={() => setProductPanel(true)} className="inline-flex items-center gap-2 rounded-lg bg-[#cf6637] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#b9552c]"><Plus size={17} />Add Product</button></div>}{section === 'banners' && <button className="inline-flex items-center gap-2 rounded-lg bg-[#cf6637] px-4 py-2.5 text-sm font-bold text-white"><Plus size={17} />Add New Banner</button>}{section === 'pricing' && <button className="rounded-lg bg-[#cf6637] px-4 py-2.5 text-sm font-bold text-white">Save All Changes</button>}</div>
      {section === 'dashboard' && <Dashboard setSection={setSection} />}
      {section === 'products' && <><LiveProductQueue /><Products items={filteredProducts} /></>}
      <OperationsPanel section={section} />
      {section === 'banners' && <Banners />}
      {section === 'orders' && <Orders filter={orderFilter} setFilter={setOrderFilter} />}
      {section === 'vendors' && <Vendors />}
      {section === 'pricing' && <Pricing />}
      {section === 'settings' && <SettingsPage />}
    </main>
    {productPanel && <ProductPanel onClose={() => setProductPanel(false)} />}
  </div>;
}

function Dashboard({ setSection }: { setSection: (section: Section) => void }) { const top = products.slice(0, 5); return <><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{[['Total Revenue', '$84,320', '+12.4% vs last month'], ['Total Orders', '1,847', '+8.1% vs last month'], ['Active Products', '342', 'Across 8 categories'], ['Pending Vendors', '14', 'Needs review']].map(([label, value, note], i) => <Card key={label} className="p-6"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-extrabold">{value}</p><p className={`mt-2 text-sm font-semibold ${i < 2 ? 'text-emerald-600' : i === 3 ? 'text-amber-600' : 'text-slate-400'}`}>{note}</p></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.9fr_0.95fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-[#eee4dc] p-6"><h2 className="text-lg font-extrabold">Recent Orders</h2><button onClick={() => setSection('orders')} className="text-sm font-bold text-[#cf6637]">View All</button></div><OrdersTable rows={orders.slice(0, 5)} compact /></Card><Card className="p-6"><h2 className="mb-5 text-lg font-extrabold">Top Products This Week</h2><div className="space-y-5">{top.map((product, i) => <div key={product.name} className="flex items-center gap-3"><img src={product.image} alt="" className="h-12 w-12 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{product.name}</p><p className="text-xs text-slate-500">{142 - i * 18} units sold</p></div><strong className="text-sm text-[#cf6637]"><Money value={product.price * (i + 20)} /></strong></div>)}</div></Card></div></>; }
function Products({ items }: { items: typeof products }) { return <Card className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-[#eadfd6] bg-[#fdfaf8] text-slate-500"><tr>{['', 'Image', 'Product Name', 'Category', 'Price', 'Stock', 'Status', 'Actions'].map((h) => <th key={h} className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{items.map((p) => <tr key={p.name} className="border-b border-[#f1ece7] last:border-0"><td className="px-5"><input type="checkbox" /></td><td className="px-5 py-3"><img src={p.image} alt="" className="h-10 w-10 rounded-lg object-cover" /></td><td className="px-5 py-3 font-bold">{p.name}</td><td className="px-5 py-3 text-slate-500">{p.category}</td><td className="px-5 py-3 font-semibold"><Money value={p.price} /></td><td className="px-5 py-3 text-slate-600">{p.stock}</td><td className="px-5 py-3"><Status>{p.status}</Status></td><td className="px-5 py-3"><div className="flex gap-3 text-slate-400"><Pencil size={17} /><Trash2 size={17} /></div></td></tr>)}</tbody></table></Card>; }
function Banners() { return <div className="grid gap-6 xl:grid-cols-[1.8fr_0.85fr]"><div className="space-y-4">{banners.map((b) => <Card key={b.slot} className="flex items-center gap-4 p-4"><GripVertical className="text-slate-400" /><img src={b.image} alt="" className="h-24 w-48 rounded-xl object-cover" /><div className="min-w-0 flex-1"><div className="mb-1 flex gap-2"><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase">{b.slot}</span><Status>Active</Status></div><p className="font-extrabold">{b.title}</p><p className="text-sm text-slate-500">{b.subtitle}</p></div><div className="flex gap-2"><button className="rounded-lg border p-2 text-slate-500"><Pencil size={17} /></button><button className="rounded-lg border p-2 text-red-500"><Trash2 size={17} /></button></div></Card>)}</div><BannerForm /></div>; }
function Orders({ filter, setFilter }: { filter: 'All' | OrderStatus; setFilter: (filter: 'All' | OrderStatus) => void }) { const rows = filter === 'All' ? orders : orders.filter((order) => order.status === filter); return <><div className="mb-3 flex flex-wrap gap-2">{(['All', 'Pending', 'Processing', 'Delivered', 'Cancelled'] as const).map((status) => <button key={status} onClick={() => setFilter(status)} className={`rounded-full border px-4 py-2 text-sm font-semibold ${filter === status ? 'border-[#1e1f21] bg-[#1e1f21] text-white' : 'border-[#ead8ca] bg-white text-slate-600'}`}>{status}</button>)}</div><Card className="overflow-x-auto"><OrdersTable rows={rows} /></Card></>; }
function OrdersTable({ rows, compact = false }: { rows: typeof orders; compact?: boolean }) { return <table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-[#eadfd6] bg-[#fdfaf8] text-slate-500"><tr>{['Order ID', ...(compact ? ['Customer', 'Product', 'Amount'] : ['Date', 'Customer', 'Items', 'Total', 'Payment Method']), 'Status', ...(compact ? [] : ['Actions'])].map((h) => <th key={h} className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.map((order) => <tr key={order.id} className="border-b border-[#f1ece7] last:border-0"><td className="px-5 py-4 font-bold">{order.id}</td>{compact ? <><td className="px-5 py-4 text-slate-600">{order.customer}</td><td className="px-5 py-4 text-slate-600">{order.product}</td><td className="px-5 py-4 font-semibold"><Money value={order.total} /></td></> : <><td className="px-5 py-4 text-slate-500">Oct 24, 2026</td><td className="px-5 py-4">{order.customer}</td><td className="px-5 py-4 text-slate-500">1 item</td><td className="px-5 py-4 font-semibold"><Money value={order.total} /></td><td className="px-5 py-4 text-slate-500">Credit Card</td></>}<td className="px-5 py-4"><Status>{order.status}</Status></td>{!compact && <td className="px-5 py-4 text-right font-semibold text-[#cf6637]">View</td>}</tr>)}</tbody></table>; }
function Vendors() { const pending = ['Lumina Tech', 'Oasis Living', 'Aura Beauty']; const active = ['Nexus Tech', 'Zenith Apparel', 'Strive Sports', 'Urban Decor']; return <div className="space-y-8"><TableTitle title="Pending Applications (3)" /><VendorTable names={pending} pending /><TableTitle title="Active Vendors" /><VendorTable names={active} /></div>; }
function TableTitle({ title }: { title: string }) { return <h2 className="mb-4 text-lg font-extrabold">{title}</h2>; }
function VendorTable({ names, pending = false }: { names: string[]; pending?: boolean }) { return <Card className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-[#fdfaf8] text-slate-500"><tr>{(pending ? ['Business Name', 'Owner', 'Category', 'Applied Date', 'Status', 'Actions'] : ['Business Name', 'Owner', 'Products Listed', 'Total Sales', 'Rating', 'Status', 'Actions']).map((h) => <th key={h} className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{names.map((name, i) => <tr key={name} className="border-b last:border-0"><td className="px-5 py-4 font-bold">{name}</td><td className="px-5 py-4 text-slate-600">{pending ? 'Jane Doe' : 'John Smith'}</td>{pending ? <><td className="px-5 py-4 text-slate-500">Various</td><td className="px-5 py-4 text-slate-500">Oct 22, 2026</td><td className="px-5 py-4"><Status>Pending</Status></td><td className="px-5 py-4 text-right"><button className="mr-2 rounded bg-emerald-100 px-3 py-1 font-bold text-emerald-700">Approve</button><button className="rounded bg-red-100 px-3 py-1 font-bold text-red-700">Reject</button></td></> : <><td className="px-5 py-4 text-slate-500">42</td><td className="px-5 py-4 font-bold text-[#cf6637]">$12,450</td><td className="px-5 py-4 text-amber-600">{(4.8 - i / 10).toFixed(1)}</td><td className="px-5 py-4"><Status>Active</Status></td><td className="px-5 py-4 text-right font-semibold text-[#cf6637]">View <span className="ml-4 text-red-500">Suspend</span></td></>}</tr>)}</tbody></table></Card>; }
function Pricing() { return <Card className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="border-b bg-[#fdfaf8] text-slate-500"><tr>{['Product Name', 'Current Price ($)', 'Sale Price ($)', 'Discount %', 'Cost Price ($)', 'Margin %', 'Quick Actions'].map((h) => <th key={h} className="px-4 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{products.map((p) => <tr key={p.name} className="border-b last:border-0"><td className="px-4 py-4 font-bold">{p.name}</td><td className="px-4"><input defaultValue={p.price} className="w-24 rounded border border-slate-300 p-1.5" /></td><td className="px-4"><input defaultValue="0.00" className="w-24 rounded border border-slate-300 p-1.5" /></td><td className="px-4 text-slate-500">-</td><td className="px-4"><input defaultValue={(p.price * .4).toFixed(2)} className="w-24 rounded border border-slate-300 p-1.5" /></td><td className="px-4 font-bold text-emerald-600">60%</td><td className="px-4 font-semibold text-[#cf6637]">Apply Sale</td></tr>)}</tbody></table><div className="flex items-center gap-3 bg-[#f8fafc] p-4 text-sm font-bold">Apply Bulk Discount: <select className="rounded border border-[#ead8ca] bg-white p-2 font-normal"><option>All Categories</option></select><input placeholder="%" className="w-20 rounded border border-[#ead8ca] p-2 font-normal" /><button className="rounded bg-[#1e1f21] px-4 py-2 text-white">Apply</button></div></Card>; }
function SettingsPage() { return <div className="grid max-w-4xl gap-7 md:grid-cols-2"><SettingsCard title="General Settings"><Field label="Store Name"><input defaultValue="DUOBRO MART" /></Field><Field label="Store Email"><input defaultValue="duobroelite@gmail.com" /></Field><Field label="Store Currency"><select><option>PKR (Rs)</option></select></Field></SettingsCard><SettingsCard title="Shipping Settings"><Field label="Default Shipping Rate (Rs)"><input defaultValue="250" /></Field><Field label="Free Shipping Threshold (Rs)"><input defaultValue="3,000" /></Field><Field label="Handling Time"><select><option>1-2 Business Days</option></select></Field></SettingsCard><SettingsCard title="Payment Settings"><Toggle label="Cash on Delivery" /><Toggle label="Bank transfer" on={false} /></SettingsCard><SettingsCard title="Email Notifications"><Toggle label="New Orders" /><Toggle label="New Vendor Applications" /><Toggle label="Low Stock Alerts" /></SettingsCard><button className="justify-self-start rounded-xl bg-[#1e1f21] px-6 py-3 text-sm font-bold text-white">Save Settings</button></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm font-bold">{label}<span className="mt-1.5 block [&>input]:w-full [&>input]:rounded-lg [&>input]:border [&>input]:border-[#ead8ca] [&>input]:p-2.5 [&>select]:w-full [&>select]:rounded-lg [&>select]:border [&>select]:border-[#ead8ca] [&>select]:bg-white [&>select]:p-2.5">{children}</span></label>; }
function SettingsCard({ title, children }: { title: string; children: ReactNode }) { return <Card className="space-y-4 p-6"><h2 className="border-b border-[#eee4dc] pb-3 text-lg font-extrabold">{title}</h2>{children}</Card>; }
function Toggle({ label, on = true }: { label: string; on?: boolean }) { return <div className="flex items-center justify-between text-sm font-semibold"><span>{label}</span><span className={`h-6 w-11 rounded-full p-1 ${on ? 'bg-[#cf6637]' : 'bg-slate-200'}`}><span className={`block h-4 w-4 rounded-full bg-white transition-transform ${on ? 'translate-x-5' : ''}`} /></span></div>; }
function ProductPanel({ onClose }: { onClose: () => void }) { return <aside className="fixed inset-y-0 right-0 z-20 w-full max-w-md overflow-y-auto border-l border-[#eee4dc] bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b bg-white p-6"><h2 className="text-lg font-extrabold">Add New Product</h2><button onClick={onClose}><X className="text-slate-400" /></button></div><form className="space-y-4 p-6"><Field label="Product Name"><input placeholder="Enter product name" /></Field><Field label="Category"><select><option>Electronics</option><option>Fashion</option><option>Home & Living</option></select></Field><Field label="Description"><textarea placeholder="Product description..." className="w-full rounded-lg border border-[#ead8ca] p-3" rows={4} /></Field><div className="grid grid-cols-2 gap-4"><Field label="Price (Rs)"><input placeholder="0.00" /></Field><Field label="Sale Price (Rs)"><input placeholder="0.00" /></Field><Field label="Stock Quantity"><input placeholder="0" /></Field><Field label="SKU"><input placeholder="SKU-..." /></Field></div><label className="grid h-36 place-items-center rounded-xl border-2 border-dashed border-[#e7cfba] text-center text-sm font-semibold text-[#cf6637]"><span><Upload className="mx-auto mb-2 text-slate-400" />Click to upload images</span><input type="file" className="hidden" /></label><div className="flex gap-3 border-t pt-4"><button type="button" onClick={onClose} className="flex-1 rounded-lg border border-[#ead8ca] py-3 font-bold">Cancel</button><button className="flex-1 rounded-lg bg-[#cf6637] py-3 font-bold text-white">Save Product</button></div></form></aside>; }
function BannerForm() { return <Card className="h-fit p-6"><h2 className="mb-5 text-lg font-extrabold">Add Banner</h2><label className="grid h-36 place-items-center rounded-xl border-2 border-dashed border-[#e7cfba] text-center text-sm font-semibold text-[#cf6637]"><span><Image className="mx-auto mb-2 text-slate-400" />Click to upload or drag & drop<br /><small className="font-normal text-slate-400">1920×1080 recommended</small></span></label><div className="mt-4 space-y-3"><Field label="Banner Title"><input placeholder="Title text" /></Field><Field label="Subtitle"><input placeholder="Subtitle text" /></Field><div className="grid grid-cols-2 gap-3"><Field label="CTA Text"><input placeholder="e.g. Shop Now" /></Field><Field label="CTA Link"><input placeholder="/category/..." /></Field></div><Field label="Position"><select><option>Hero Slot 1</option></select></Field><label className="flex items-center gap-2 text-sm font-semibold"><input defaultChecked type="checkbox" className="accent-[#cf6637]" />Set as Active</label><button className="w-full rounded-lg bg-[#1e1f21] py-3 font-bold text-white">Publish Banner</button></div></Card>; }
