import { useEffect, useState } from 'react';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api';
type Props = { section: 'vendors' | 'pricing' | 'settings' | 'dashboard' | 'products' | 'banners' | 'orders' };
type Application = { id: number; full_name: string; business_name: string; status: string };
type Request = { id: number; kind: string; value: string; status: string };
export default function OperationsPanel({ section }: Props): JSX.Element | null {
  const [applications, setApplications] = useState<Application[]>([]); const [requests, setRequests] = useState<Request[]>([]); const [settings, setSettings] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const auth = { Authorization: `Bearer ${localStorage.getItem('duobro_access') || ''}` };
  const load = () => { if (section === 'vendors') fetch(`${API}/admin/vendor-applications/`, { headers: auth }).then((r) => r.json()).then(setApplications).catch(() => setMessage('Unable to load applications.')); if (section === 'pricing') fetch(`${API}/admin/requests/`, { headers: auth }).then((r) => r.json()).then((data) => setRequests(data.results || data)).catch(() => setMessage('Unable to load requests.')); if (section === 'settings') fetch(`${API}/admin/settings/`, { headers: auth }).then((r) => r.json()).then(setSettings).catch(() => setMessage('Unable to load settings.')); };
  useEffect(load, [section]);
  const decide = async (url: string, status: string) => { await fetch(url, { method: 'POST', headers: { ...auth, 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); load(); };
  if (!['vendors', 'pricing', 'settings'].includes(section)) return null;
  return <section className="mb-6 rounded-2xl border border-[#ead8ca] bg-white p-5"><h2 className="font-bold">Live operations</h2>{message && <p className="mt-2 text-sm text-red-600">{message}</p>}{section === 'vendors' && <div className="mt-4 space-y-2">{applications.filter((item) => item.status === 'pending').map((item) => <div key={item.id} className="flex justify-between gap-3 rounded-lg bg-amber-50 p-3 text-sm"><span>{item.full_name} · {item.business_name}</span><span className="space-x-2"><button onClick={() => decide(`${API}/admin/vendor-applications/${item.id}/decision/`, 'approved')} className="rounded bg-emerald-600 px-2 py-1 text-white">Approve</button><button onClick={() => decide(`${API}/admin/vendor-applications/${item.id}/decision/`, 'rejected')} className="rounded bg-red-600 px-2 py-1 text-white">Reject</button></span></div>)}</div>}{section === 'pricing' && <div className="mt-4 space-y-2">{requests.filter((item) => item.status === 'pending').map((item) => <div key={item.id} className="flex justify-between rounded-lg bg-amber-50 p-3 text-sm"><span>{item.kind}: {item.value}</span><button onClick={() => decide(`${API}/admin/requests/${item.id}/decision/`, 'approved')} className="rounded bg-emerald-600 px-2 py-1 text-white">Approve</button></div>)}</div>}{section === 'settings' && <form onSubmit={async (event) => { event.preventDefault(); await fetch(`${API}/admin/settings/`, { method: 'PUT', headers: { ...auth, 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); setMessage('Settings saved.'); }} className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(settings).filter(([key]) => key !== 'id').map(([key, value]) => <label key={key} className="text-xs font-bold">{key}<input value={value} onChange={(event) => setSettings({ ...settings, [key]: event.target.value })} className="mt-1 block w-full rounded border p-2 text-sm" /></label>)}<button className="rounded bg-[#cf6637] px-4 py-2 text-sm font-bold text-white">Save settings</button></form>}</section>;
}
