import { useEffect, useState } from 'react';
import { LogOut, PackagePlus, Store } from 'lucide-react';
import { fetchCatalogMetadata, submitVendorProduct } from '../api/catalog';

export default function VendorPanel({ name, onLogout }: { name: string; onLogout: () => void }): JSX.Element {
  const [categories, setCategories] = useState<{ id: number; name: string }[]>([]); const [brands, setBrands] = useState<{ id: number; name: string }[]>([]); const [message, setMessage] = useState('');
  useEffect(() => { fetchCatalogMetadata().then((data) => { setCategories(data.categories); setBrands(data.brands); }).catch(() => setMessage('Catalog options are unavailable.')); }, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await submitVendorProduct(localStorage.getItem('duobro_access') || '', Object.fromEntries(form.entries()) as Record<string, string>); setMessage('Product submitted for admin approval.'); event.currentTarget.reset(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to submit product.'); } };
  const submitRequest = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch('http://localhost:8000/api/vendor/requests/', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('duobro_access') || ''}` }, body: JSON.stringify(form) }); setMessage(response.ok ? 'Request sent for admin approval.' : 'Unable to send request.'); };
  return <main className="min-h-screen bg-[#FBF7EF] px-5 py-10 text-[#101A2E] sm:px-8"><section className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-5 border-b border-[#e8ddd2] pb-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#F2A93B]"><Store size={21} /></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#E0912A]">Vendor panel</p><h1 className="text-2xl font-extrabold">Welcome, {name}</h1></div></div><button onClick={onLogout} className="inline-flex items-center gap-2 rounded-xl border border-[#d6c9bb] bg-white px-4 py-2.5 text-sm font-bold"><LogOut size={16} /> Log out</button></header><form onSubmit={submit} className="mt-10 rounded-2xl border border-[#e8ddd2] bg-white p-8 shadow-sm"><PackagePlus className="mb-4 text-[#E0912A]" size={32} /><h2 className="text-xl font-bold">Submit a product</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><input required name="name" placeholder="Product name" className="rounded-xl border p-3" /><input required name="price" type="number" min="1" placeholder="Price (PKR)" className="rounded-xl border p-3" /><input required name="stock" type="number" min="0" placeholder="Stock" className="rounded-xl border p-3" /><input name="image_url" type="url" placeholder="Image URL" className="rounded-xl border p-3" /><select required name="category" className="rounded-xl border p-3"><option value="">Category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required name="brand" className="rounded-xl border p-3"><option value="">Brand</option>{brands.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><textarea required name="description" placeholder="Product description" className="min-h-28 rounded-xl border p-3 sm:col-span-2" /></div><button className="mt-5 rounded-xl bg-[#101A2E] px-5 py-3 text-sm font-bold text-white">Submit for approval</button>{message && <p className="mt-4 text-sm text-[#5B6B85]">{message}</p>}</form><form onSubmit={submitRequest} className="mt-6 rounded-2xl border border-[#e8ddd2] bg-white p-6"><h2 className="font-bold">Price, deal, or restock request</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><input required name="product" type="number" placeholder="Product ID" className="rounded border p-3" /><select name="kind" className="rounded border p-3"><option value="price">Price</option><option value="deal">Deal</option><option value="restock">Restock</option></select><input required name="value" placeholder="New price, deal %, or quantity" className="rounded border p-3" /></div><button className="mt-4 rounded bg-[#cf6637] px-4 py-2 text-sm font-bold text-white">Send request</button></form></section></main>;
}
